create table public.ledger_transactions
(
    state_version                   bigint                    not null
        constraint "PK_ledger_transactions"
            primary key,
    created_at                      timestamp with time zone  not null
);

alter table public.ledger_transactions
    owner to db_dev_superuser;

create table public.entity_definitions
(
    id                                              bigint generated by default as identity
        constraint "PK_entity_definitions"
            primary key,
    from_state_version                              bigint      not null,
    address                                         text        not null
);

alter table public.entity_definitions
    owner to db_dev_superuser;

create unique index "IX_entity_definitions_a"
    on public.entity_definitions (address);

create table public.metadata_entry_history
(
    id                 bigint generated by default as identity
        constraint "PK_metadata_entry_history"
            primary key,
    from_state_version bigint  not null,
    entity_id          bigint  not null,
    key                bytea   not null,
    value              bytea
);

alter table public.metadata_entry_history
    owner to db_dev_superuser;

create index "IX_metadata_entry_history_a"
    on public.metadata_entry_history (entity_id, key, from_state_version);

create table public.metadata_aggregate_history
(
    id                 bigint generated by default as identity
        constraint "PK_metadata_aggregate_history"
            primary key,
    from_state_version bigint   not null,
    entity_id          bigint   not null,
    entry_ids          bigint[] not null
);

alter table public.metadata_aggregate_history
    owner to db_dev_superuser;

create index "IX_metadata_aggregate_history_a"
    on public.metadata_aggregate_history (entity_id, from_state_version);

-- maintenance
truncate ledger_transactions;
truncate entity_definitions;
truncate metadata_entry_history;
truncate metadata_aggregate_history;
select setval('entity_definitions_id_seq', 1), setval('metadata_entry_history_id_seq', 1), setval('metadata_aggregate_history_id_seq', 1);
