version: '3.8'

services:
  core:
    container_name: radixdlt-babylon-node
    build:
      context: ../.
      dockerfile: Dockerfile
    environment:
      RADIXDLT_LOG_LEVEL: info
      RADIXDLT_CORE_API_PORT: 3333
      RADIXDLT_SYSTEM_API_PORT: 3334
      RADIXDLT_PROMETHEUS_API_PORT: 3335
      RADIXDLT_ENGINE_STATE_API_PORT: 3336
      RADIXDLT_MESH_API_PORT: 3337
      RADIXDLT_GENESIS_DATA: ${RADIXDLT_GENESIS_DATA}
      JAVA_OPTS: -server -Xmx512m -Xmx512m -XX:+HeapDumpOnOutOfMemoryError -XX:+AlwaysPreTouch -Dguice_bytecode_gen_option=DISABLED -Djavax.net.ssl.trustStore=/etc/ssl/certs/java/cacerts -Djavax.net.ssl.trustStoreType=jks -Djava.security.egd=file:/dev/urandom -Dcom.sun.management.jmxremote.port=9011 -Dcom.sun.management.jmxremote.rmi.port=9011 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=core -agentlib:jdwp=transport=dt_socket,address=*:50505,suspend=n,server=y --enable-preview
      # Adjust the following envvar for trace collection
      # JAEGER_AGENT_ENDPOINT: jaeger:6831
    labels:
      com.radixdlt.roles: "core"
    logging:
      options:
        max-size: "10m"
        max-file: "30"
