FROM eclipse-temurin:17-alpine
LABEL org.opencontainers.image.authors="devops@radixdlt.com"

RUN mkdir -p /keygen/bin keygen/lib

COPY bin/ /keygen/bin
COPY lib/ /keygen/lib
WORKDIR /keygen/

ENTRYPOINT ["bin/keygen"]