version: '3.8'
name: radixdlt-babylon-node-network-size-1
services:
  core1:
    container_name: radixdlt-babylon-node-0
    extends:
      file: core.yml
      service: core
    environment:
      RADIXDLT_HOST_IP_ADDRESS: core0
      RADIXDLT_NETWORK_SEEDS_REMOTE: "radix://${RADIXDLT_VALIDATOR_0_PUBKEY}@core0"
      RADIXDLT_NODE_KEY: ${RADIXDLT_VALIDATOR_0_PRIVKEY}
    networks:
      - single_node
    ports:
      - "3333:3333"   # Core API
      - "3334:3334"   # System API
      - "3335:3335"   # Prometheus API
      - "3336:3336"   # Engine State API
      - "9011:9011"   # JMX Port for Java debugging
      - "50505:50505" # JDWP Port for Java debugging
      # Gossip port on 30000 can be called by other nodes inside docker, but isn't exposed outside docker
networks:
  single_node:
