name: Deploy

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  cancel_running_workflows:
    name: Cancel running workflows
    runs-on: ubuntu-22.04
    steps:
      - name: cancel running workflows
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
  deploy:
    name: Deploy to Gilganet
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy to testnet
        uses: toptal/jenkins-job-trigger-action@1.0.0
        with:
          jenkins_url: "${{ secrets.JENKINS_URL }}"
          jenkins_user: ${{ secrets.JENKINS_USER }}
          jenkins_token: ${{ secrets.BABYLON_NODE_JENKINS_API_TOKEN }}
          job_name: "ephemeral-deployments/job/ephemeral-env-deploy-and-test"
          job_params: |
            {
              
            }
          job_timeout: "3600"