name: 'Setup version properties'
description: 'Get version information from Git, used by gradle'
on:
  workflow_call:
    outputs:
      VERSION_BRANCH:
        description:
        value: ${{ jobs.setup_version_properties.outputs.VERSION_BRANCH }}
      VERSION_BUILD:
        description:
        value: ${{ jobs.setup_version_properties.outputs.VERSION_BUILD }}
      VERSION_COMMIT:
        description:
        value: ${{ jobs.setup_version_properties.outputs.VERSION_COMMIT }}
      VERSION_DISPLAY:
        description:
        value: ${{ jobs.setup_version_properties.outputs.VERSION_DISPLAY }}
      VERSION_TAG:
        description:
        value: ${{ jobs.setup_version_properties.outputs.VERSION_TAG }}

jobs:
  setup_version_properties:
    name: Setup version properties
    runs-on: ubuntu-latest
    outputs:
      VERSION_BRANCH: ${{ steps.setup_version_properties.outputs.VERSION_BRANCH }}
      VERSION_BUILD: ${{ steps.setup_version_properties.outputs.VERSION_BUILD }}
      VERSION_COMMIT: ${{ steps.setup_version_properties.outputs.VERSION_COMMIT }}
      VERSION_DISPLAY: ${{ steps.set_display_version.outputs.VERSION_DISPLAY }}
      VERSION_TAG: ${{ steps.setup_version_properties.outputs.VERSION_TAG }}
    steps:
      - uses: RDXWorks-actions/checkout@main
        with:
          fetch-depth: 0
      - id: setup_version_properties
        run: |
          echo "VERSION_BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
          echo "VERSION_BUILD=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "VERSION_COMMIT=${GITHUB_SHA}" >> $GITHUB_OUTPUT
          if [[  $GITHUB_REF == *"refs/tags/"* ]]; then 
            echo "VERSION_TAG=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_OUTPUT
          fi
        shell: bash
      - id: set_display_version
        run: |
          if [ -z "${VERSION_TAG}" ]; then
            echo "VERSION_DISPLAY=$VERSION_BRANCH-$VERSION_BUILD" >> $GITHUB_OUTPUT
          else
            echo "VERSION_DISPLAY=$VERSION_TAG" >> $GITHUB_OUTPUT
          fi
        shell: bash
